/*
 * Conflux FFI - C bindings for multi-stream message synchronization
 *
 * This header is auto-generated by cbindgen. Do not edit manually.
 *
 * License: MIT OR Apache-2.0
 */

#ifndef CONFLUX_FFI_H
#define CONFLUX_FFI_H

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is auto-generated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Policy for handling buffer overflow when pushing new messages.
 */
typedef enum ConfluxDropPolicy {
    /**
     * Reject new messages when buffer is full.
     * Preserves existing data. Suitable for offline/rosbag processing.
     */
    ConfluxDropPolicy_RejectNew = 0,
    /**
     * Drop the oldest message to make room for the new one.
     * Always accepts new data. Suitable for realtime processing.
     */
    ConfluxDropPolicy_DropOldest = 1,
} ConfluxDropPolicy;

/**
 * Result codes for FFI operations.
 */
typedef enum ConfluxResult {
    /**
     * Operation succeeded.
     */
    ConfluxResult_Ok = 0,
    /**
     * Invalid argument provided.
     */
    ConfluxResult_InvalidArgument = 1,
    /**
     * Buffer is full, message rejected.
     */
    ConfluxResult_BufferFull = 2,
    /**
     * Key not found.
     */
    ConfluxResult_KeyNotFound = 3,
    /**
     * Null pointer provided.
     */
    ConfluxResult_NullPointer = 4,
    /**
     * Internal error.
     */
    ConfluxResult_InternalError = 5,
    /**
     * Message rejected: timestamp is before the commit time (arrived too late).
     */
    ConfluxResult_LateMessage = 6,
    /**
     * Message rejected: timestamp is not monotonically increasing.
     */
    ConfluxResult_OutOfOrder = 7,
    /**
     * Timed out waiting for buffer space (blocking push only).
     */
    ConfluxResult_Timeout = 8,
} ConfluxResult;

/**
 * Why the matcher is not currently emitting, mirroring `conflux_core::BlockedReason`.
 */
typedef enum ConfluxBlockedReason {
    /**
     * A group is available right now -- nothing is blocked.
     */
    ConfluxBlockedReason_NotBlocked = 0,
    /**
     * At least one stream has delivered nothing yet.
     */
    ConfluxBlockedReason_WaitingForData = 1,
    /**
     * All streams have data, but everything sits inside a band narrower than
     * the window, so the matcher is holding out for a better pairing.
     */
    ConfluxBlockedReason_SpreadTooNarrow = 2,
    /**
     * A buffer is at capacity and no group fits the window. Does not resolve on
     * its own; `conflux_poll` forces progress out of it (C-05).
     */
    ConfluxBlockedReason_BufferFullNoMatch = 3,
} ConfluxBlockedReason;

/**
 * Opaque handle to a synchronizer instance.
 *
 * The synchronizer manages multiple message streams and outputs
 * synchronized groups when messages fall within the configured time window.
 */
typedef struct ConfluxSynchronizer ConfluxSynchronizer;

/**
 * Configuration for creating a synchronizer.
 */
typedef struct ConfluxConfig {
    /**
     * Time window in milliseconds for grouping messages.
     * Use 0 for infinite window (no time-based dropping).
     */
    uint64_t window_size_ms;
    /**
     * Maximum number of messages to buffer per stream.
     */
    uintptr_t buffer_size;
    /**
     * Policy for handling buffer overflow.
     */
    enum ConfluxDropPolicy drop_policy;
} ConfluxConfig;

/**
 * A snapshot of the matcher's own view, for diagnosing why nothing is emitted.
 *
 * M-23: timestamps are nanoseconds, and `-1` means "not applicable" (some
 * buffer is empty, or the window is infinite so nothing is being waited for).
 */
typedef struct ConfluxStatus {
    /**
     * Greatest of the per-stream oldest timestamps, or -1.
     */
    int64_t inf_ts_ns;
    /**
     * Least of the per-stream newest timestamps, or -1.
     */
    int64_t sup_ts_ns;
    /**
     * `sup_ts - inf_ts`, or -1.
     */
    int64_t spread_ns;
    /**
     * Additional spread needed before the matcher stops waiting, or -1.
     */
    int64_t shortfall_ns;
    /**
     * Why no group is available.
     */
    enum ConfluxBlockedReason blocked;
} ConfluxStatus;

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

/**
 * Create a new synchronizer with the given configuration and keys.
 *
 * # Safety
 *
 * - `keys` must be an array of `key_count` valid null-terminated C strings.
 * - Returns a pointer to a new synchronizer instance. The caller is responsible
 *   for freeing this with `conflux_synchronizer_free`.
 */
struct ConfluxSynchronizer* conflux_synchronizer_new(const struct ConfluxConfig* config,
                                                     const char* const* keys, uintptr_t key_count);

/**
 * Free a synchronizer instance.
 *
 * # Safety
 *
 * The pointer must have been returned by `conflux_synchronizer_new` and must
 * not be used after this call.
 */
void conflux_synchronizer_free(struct ConfluxSynchronizer* sync);

/**
 * Read the matcher's current status.
 *
 * M-23: the input-side counters cannot tell a healthy wait from a stall. This
 * reports what the matcher itself sees, so a caller can answer "why is it not
 * matching?" without attaching a debugger.
 *
 * # Safety
 *
 * - `sync` must be a valid pointer from `conflux_synchronizer_new`.
 * - `out` must point to a writable `ConfluxStatus`.
 */
enum ConfluxResult conflux_get_status(const struct ConfluxSynchronizer* sync,
                                      struct ConfluxStatus* out);

/**
 * Discard all buffered messages and forget all timestamp history.
 *
 * M-22: call this when the message source restarts its clock -- a rosbag loop,
 * a sim-time reset, or a sensor that reconnects and restarts its stamp counter.
 * Without it the affected buffer rejects every later message as out-of-order
 * forever, and because a group needs all streams non-empty, one dead stream
 * stalls the entire synchronizer with no way back.
 *
 * Buffered messages are dropped. Callers holding references keyed by
 * `user_data` should reconcile with `conflux_for_each_live` after this call --
 * which will report nothing live, since every buffer is now empty.
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
void conflux_synchronizer_reset(struct ConfluxSynchronizer* sync);

/**
 * Push a message to the synchronizer.
 *
 * # Safety
 *
 * - `sync` must be a valid pointer from `conflux_synchronizer_new`.
 * - `key` must be a valid null-terminated C string for a key provided at creation.
 * - `user_data` is an opaque pointer that will be returned in synchronized groups.
 *
 * # Returns
 *
 * - `ConfluxResult::Ok` if the message was accepted.
 * - `ConfluxResult::BufferFull` if the buffer for this key is full.
 * - `ConfluxResult::KeyNotFound` if the key was not provided at creation.
 */
enum ConfluxResult conflux_push_message(struct ConfluxSynchronizer* sync, const char* key,
                                        int64_t timestamp_ns, void* user_data);

/**
 * Poll for a synchronized group of messages.
 *
 * This function checks if there's a complete synchronized group available
 * and returns it via the callback.
 *
 * # Safety
 *
 * - `sync` must be a valid pointer from `conflux_synchronizer_new`.
 * - `callback` will be called with each key-value pair in the synchronized group.
 * - `context` is passed through to the callback.
 *
 * # Callback
 *
 * The callback receives:
 * - `key`: The topic/key name (null-terminated string)
 * - `timestamp_ns`: Message timestamp in nanoseconds
 * - `user_data`: The user data pointer passed to `conflux_push_message`
 * - `context`: The context pointer passed to this function
 *
 * # Returns
 *
 * - 1 if a synchronized group was found and callback was invoked.
 * - 0 if no synchronized group is available.
 * - -1 on error.
 */
int32_t conflux_poll(struct ConfluxSynchronizer* sync,
                     void (*callback)(const char* key, int64_t timestamp_ns, void* user_data,
                                      void* context),
                     void* context);

/**
 * Invoke `callback` once for every message currently held in a buffer, passing
 * its `user_data`.
 *
 * C-02: DropOldest eviction and finite-window pruning discard messages silently
 * (the push still returns Ok), so a caller that keeps a table of message
 * references keyed by `user_data` (e.g. the Python binding) never learns they
 * were dropped and leaks one reference per evicted message. This lets the caller
 * reconcile its table against the set of still-live messages and free the rest.
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
void conflux_for_each_live(const struct ConfluxSynchronizer* sync,
                           void (*callback)(void* user_data, void* context), void* context);

/**
 * Get the number of keys registered with the synchronizer.
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
uintptr_t conflux_key_count(const struct ConfluxSynchronizer* sync);

/**
 * Check if the synchronizer is ready (all buffers have at least 2 messages).
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
bool conflux_is_ready(const struct ConfluxSynchronizer* sync);

/**
 * Check if the synchronizer is empty (any buffer is empty).
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 *
 * L-17: prefer `conflux_has_empty_buffer`. The name `is_empty` reads as "the
 * synchronizer holds nothing", but it reports whether ANY buffer is empty.
 * Retained so existing callers keep linking.
 */
bool conflux_is_empty(const struct ConfluxSynchronizer* sync);

/**
 * Returns true when **at least one** buffer is empty, i.e. no group can form.
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
bool conflux_has_empty_buffer(const struct ConfluxSynchronizer* sync);

/**
 * Returns true when **every** buffer is empty -- the synchronizer is idle.
 *
 * # Safety
 *
 * `sync` must be a valid pointer from `conflux_synchronizer_new`.
 */
bool conflux_all_buffers_empty(const struct ConfluxSynchronizer* sync);

/**
 * Get the buffer size for a specific key.
 *
 * # Safety
 *
 * - `sync` must be a valid pointer from `conflux_synchronizer_new`.
 * - `key` must be a valid null-terminated C string.
 *
 * # Returns
 *
 * The number of messages in the buffer, or 0 if the key is not found.
 */
uintptr_t conflux_buffer_len(const struct ConfluxSynchronizer* sync, const char* key);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif /* CONFLUX_FFI_H */
